# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b69ecc4276ede8450df6fa73b074079b0263b84dde4c0234dee559e8ec610b961fb8466cfdac368ce46c2e4d72a07991f80503d6f4b0322d55e3ae5be3f1afd

test:
  secret_key_base: ba241ff56ecfab4e36f6f7318c0f6ddeb5902d8a000a6bd83f295d43c2290a34376be06ff6a5928a882c07c1a8058408490414842395454864dc466bba837f48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
